### ISSUE TITLE
add new field llena to bodega model 

### ISSUE THREAD

**Issue by Japoivvb** [herjflorez/dam2tm06uf2p2-Hernando-Florez#4]
1. add llena attribute to bodega model, it sets false and changes true after vendimia

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Japoivvb** [comment]
1. ko, incompleted, it does not change to true when vendimia is done
2. ko
3. ko
4. ko
5. ok

**Comment by herjflorez** [comment]
![imagen_2024-04-09_175832732](https://github.com/herjflorez/dam2tm06uf2p2-Hernando-Florez/assets/48648845/d2a4e8ab-d4d5-46f6-af86-88021b47f019)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
I updated the mark also
