### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [herjflorez/dam2tm06uf2p2-Hernando-Florez#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by herjflorez** [comment]
![image](https://github.com/herjflorez/dam2tm06uf2p2-Hernando-Florez/assets/48648845/88522902-ffd6-43ba-a52e-23b1716b553e)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ko, that screenshot is not an evidence
5. ok
